name: Deploy Surprise Trip

on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SECURAAI_API_KEY: ${{ secrets.SECURAAI_API_KEY }}
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: SECURAAI_API_KEY
          script: |
            cd ~/projects/surprise_trip
            git pull origin main
            docker compose down --remove-orphans
            docker compose build --no-cache
            docker compose up -d
            sleep 20
            echo "--------------------- SecuraAI CLI Start ---------------------------------------------------"
            cd /home/ubuntu/projects/surprise_trip/
            python3 -m venv venv
            source venv/bin/activate
            python3 -m pip install -r requirements.txt
            curl -o securaai-cli.zip https://api-dev.securaai.com/public/securaai-cli/download
            unzip -o securaai-cli.zip
            cd securaai-cli
            chmod +x securaai-cli
            export SECURAAI_API_KEY=$SECURAAI_API_KEY
            ./securaai-cli connect
            ./securaai-cli agent-scan --agent-path /home/ubuntu/projects/surprise_trip --framework crewai --upload-agent --output report.html
            echo "--------------------- SecuraAI CLI Completed -----------------------------------------------"
            docker image prune -f
