name: Deploy Surprise Trip

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/projects/surprise_trip
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            sleep 20
            echo "--------------------- SecuraAI CLI Start ---------------------------------------------------"
            cd /home/ubuntu/projects/surprise_trip/
            curl -o securaai-cli.zip https://api-dev.securaai.com/public/securaai-cli/download
            unzip -o securaai-cli.zip
            cd securaai-cli
            chmod +x securaai-cli
            export SECURAAI_API_KEY=${{ secrets.SECURAAI_API_KEY }}
            ./securaai-cli connect
            echo "--------------------- SecuraAI CLI Completed -----------------------------------------------"
            docker image prune -f
